import React from "react";

const Home = () => {
  return (
    <div>
      <h1>Math Magicians</h1>
      <h2>Welcome to our page!</h2>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus provident nostrum soluta ipsa, quaerat distinctio itaque ea quas. Maiores quisquam atque iusto consequuntur illo? Laborum aut quas deserunt pariatur commodi veritatis eveniet facere quibusdam libero ut, expedita vero eum, accusamus soluta sunt vel, nesciunt perferendis. Modi, porro! Accusantium harum tempora error vitae, iusto exercitationem corrupti ipsum quaerat. Molestiae, sunt, incidunt eligendi deserunt ea nesciunt, laborum fuga sapiente voluptates minima quibusdam quis sed officiis? Officia aperiam aliquam iusto fuga, eaque vero recusandae, velit ut provident quod consectetur? Et, esse ducimus ab ex voluptates consequuntur deserunt, quae repudiandae doloribus quod suscipit ea optio quaerat. Consectetur laudantium id animi harum explicabo provident, sapiente accusantium tenetur, consequuntur eveniet, aspernatur facilis! Laudantium tempore mollitia, odio recusandae sit, facilis aliquid nam eligendi tempora est assumenda quo rerum reprehenderit ea odit incidunt sapiente? Cumque natus consectetur temporibus odit repellat iste eos beatae quos voluptas perferendis debitis, provident quam minima cum similique consequatur animi, fugiat sint autem libero unde? Cupiditate consequatur accusamus itaque libero ex ipsum sunt enim exercitationem excepturi repudiandae corporis vel deserunt laboriosam debitis, repellat nesciunt ratione quidem voluptatem at, qui dolore dolores perspiciatis mollitia. Numquam quam quia tempore et quasi consectetur! Mollitia, vitae aspernatur ipsa harum incidunt accusantium quo doloribus ducimus laboriosam, est quae rerum! Impedit accusantium tenetur dolor, debitis obcaecati ratione laudantium laboriosam eaque voluptate reprehenderit, odio neque. Rerum velit deleniti eius delectus sapiente veritatis labore repudiandae, aliquam quas blanditiis? Molestias voluptatum, necessitatibus repudiandae adipisci iure quis natus a neque incidunt nam nostrum quidem.</p>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus provident nostrum soluta ipsa, quaerat distinctio itaque ea quas. Maiores quisquam atque iusto consequuntur illo? Laborum aut quas deserunt pariatur commodi veritatis eveniet facere quibusdam libero ut, expedita vero eum, accusamus soluta sunt vel, nesciunt perferendis. Modi, porro! Accusantium harum tempora error vitae, iusto exercitationem corrupti ipsum quaerat. Molestiae, sunt, incidunt eligendi deserunt ea nesciunt, laborum fuga sapiente voluptates minima quibusdam quis sed officiis? Officia aperiam aliquam iusto fuga, eaque vero recusandae, velit ut provident quod consectetur? Et, esse ducimus ab ex voluptates consequuntur deserunt, quae repudiandae doloribus quod suscipit ea optio quaerat. Consectetur laudantium id animi harum explicabo provident, sapiente accusantium tenetur, consequuntur eveniet, aspernatur facilis! Laudantium tempore mollitia, odio recusandae sit, facilis aliquid nam eligendi tempora est assumenda quo rerum reprehenderit ea odit incidunt sapiente? Cumque natus consectetur temporibus odit repellat iste eos beatae quos voluptas perferendis debitis, provident quam minima cum similique consequatur animi, fugiat sint autem libero unde? Cupiditate consequatur accusamus itaque libero ex ipsum sunt enim exercitationem excepturi repudiandae corporis vel deserunt laboriosam debitis, repellat nesciunt ratione quidem voluptatem at, qui dolore dolores perspiciatis mollitia. Numquam quam quia tempore et quasi consectetur! Mollitia, vitae aspernatur ipsa harum incidunt accusantium quo doloribus ducimus laboriosam, est quae rerum! Impedit accusantium tenetur dolor, debitis obcaecati ratione laudantium laboriosam eaque voluptate reprehenderit, odio neque. Rerum velit deleniti eius delectus sapiente veritatis labore repudiandae, aliquam quas blanditiis? Molestias voluptatum, necessitatibus repudiandae adipisci iure quis natus a neque incidunt nam nostrum quidem.</p>
    </div>
  )
}

export default Home;